apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http
  namespace: ops
spec:
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - image: httpd
